### ISSUE TITLE
Version bump on pypi

### ISSUE THREAD

**Issue by max-arnold** [aaugustin/django-resto#11]
Hi Aymeric!

Could you please upload a new release to pypi?

**Comment by aaugustin** [comment]
1.3 is live on PyPI.

BTW, if you want to take over maintenance this package, I'm happy to give you the keys to the repository and to PyPI :-) Just let me know.

**Comment by max-arnold** [comment]
Thanks for the offer, but I'll have to pass on this opportunity, because we plan to move to a more robust storage system and as soon as it happens, I too will have to look for a new maintainer :)

In the meantime though, I'll be happy to send compatibility PRs.
